// Manually wired to AbdulmohsenM's external Supabase project.
// NOTE: This file is normally auto-generated by Lovable Cloud. It has been
// overridden to point at an external Supabase project. If Lovable ever
// regenerates this file, re-apply the SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY
// values below.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://uckoiaddlkyusiaokwer.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_XltnsAx-2PN8Lq_NZ6kq7w_O02feHH5';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
